[build]
  base = "she-orders-project"
  command = "npm install && npm run build"
  publish = "she-orders-project/.next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
